### ISSUE TITLE
Issue with pac4j 

### ISSUE THREAD

**Issue by h8** [leleuj/cas-pac4j-oauth-demo#15]
Hello, 

Failed to run demo, because of 

`Error creating bean with name 'clientAction' defined in ServletContext resource [/WEB-INF/cas-servlet.xml]: Instantiation of bean failed; nested exception is java.lang.NoClassDefFoundError: org/pac4j/core/client/Mechanism`

1.6.0 version of pac4j doesn't have such class, and if I change version back to 1.5.1 I've got another Class Not Found Exception - org/pac4j/core/client/Protocol, because 1.5.1 doesn't contain this class too. 

Maybe, there should be a branch for a stable version of CAS?

**Comment by leleuj** [comment]
You're right, there should be a 4.0.x branch, but I'm generaly running out of time.

It should work with 1.6.0. I just updated the pom.xml file: what do you get as an error on that case?

**Comment by h8** [comment]
Now I get Slf4j error, but I was able to run application with Tomcat installation.

**Comment by leleuj** [comment]
Yes, it's: https://github.com/leleuj/cas-pac4j-oauth-demo/issues/14. Good.
